### ISSUE TITLE
Can you add a Screenshot to your readme?

### ISSUE THREAD

**Issue by MikeTheWatchGuy** [ppalani/Mp3Player#1]
Everyone that stops into your GitHub wants to know what your MP3Player looks like.  It would be so cool to see a screenshot of it in your Readme so that we're able to see if on your GitHub homescreen.

**Comment by ppalani** [comment]
Sure adding now , sorry for the delay , just noticed this message.

**Comment by ppalani** [comment]
added the screen shot,

**Comment by PySimpleGUI** [comment]
That's a great start!

If you make one more change to your readme.md file, then it will embed the image rather than displaying the link.

Where you have placed the link currently, replace it with this:
```
![image](https://github.com/ppalani/Mp3Player/raw/master/6f2c2478-f787-4367-ae95-f46b6d07165f.jpg)
```

It should embed the image in your readme when you visit your GitHub's homepage.

It will look like this:
![image](https://github.com/ppalani/Mp3Player/raw/master/6f2c2478-f787-4367-ae95-f46b6d07165f.jpg)
